from pathlib import Path
import logging
from typing import LiteralString
from nicegui import events, ui
import secrets
import string
from shutil import rmtree
from pprint import pprint


logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


class FileManager:
    def __init__(self,
                 all_documents_directory: str = "Documents",
                 all_todos_directory_name: str = "todos_folders") -> None:
        """
        Initializes the FileManager with a path of the main folder (todos_folders") that will then store any future folders
        attached to their respective newly created todo.
        It also creates a list that is an attribute to the FileManager created object. This empty list is used a temporary storage location
        for any files that will be uploaded inside a Todo ui.upload element. When the files are definitely uploaded and saved locally, then
        this list is reset to be ready for a next upload.

        Args:
            all_todos_directory_name (str):
            all_documents_directory (str): Name of the primary table (default : "todos")

        Raises:
             OSError: if it fails to validate or create the main folder "todos_folders" absolute path.
        """
        self.all_documents_directory = all_documents_directory
        self.all_todos_directory_name = all_todos_directory_name
        self.all_todos_parent_folder_full_path: Path = Path(
            f"{Path.home()}/{all_documents_directory}/{all_todos_directory_name}")
        self.uploaded_files: list[dict[
            str, any]] = []  # Location to save temporarily any files attached to a todo and that need to be uploaded and saved locally

        # Validate target parent folder path or creates it does not exist yet
        try:
            self.all_todos_parent_folder_full_path.mkdir(parents=True, exist_ok=True)
        except OSError as error:
            logger.error(f"🛑Failed to create target directory: {error}")

        logger.info(
            f"✅FileManager initialized target directory for all todos' folders : {self.all_todos_parent_folder_full_path}")

    # PRIVATE METHODS
    @staticmethod
    def _generate_unique_folder_name(todo_name: str, max_len_code: int, max_len_folder_name: int) -> str:
        """
        Creates and returns a unique folder_name associated to a todo name.

        Args:
            todo_name (str): todo name that will be part of the folder name.
            max_len_code (int): unique sequence of chars that will precede the todo name inside the folder name.
            max_len_folder_name (int) : max length of the final todo folder name generated.

        Returns:
            unique_folder_name (str) : can be used in public methods.

        Raises:
            nothing
        """
        authorized_characters: LiteralString = string.ascii_letters + string.digits

        random_code: str = "".join(secrets.choice(authorized_characters) for _ in range(max_len_code))

        sanitized_todo_name: str = todo_name.replace(" ", "_").lower()
        truncated_sanitized_todo_name: str = sanitized_todo_name[:max_len_folder_name]

        unique_folder_name: str = f"{random_code}_{truncated_sanitized_todo_name}"

        return unique_folder_name

    # PUBLIC METHODS
    def create_folder_locally(self, todo_name: str) -> str | None:
        """
         Creates locally an unique folder that is linked to a newly created todo.

         This method will be used for every todo creation (when "Create" button will be clicked in the GUI).
         Once the folder is created, its name cannot be changed.

         It returns the created folder name, which is a string that will be saved into the SQLite database as the attachment_dir column's value.

        Args:
            todo_name (str): the todo name will be used as a part of the unique_folder_name generated by the method.

        Returns:
            todo_folder_name (str): a mix of a unique random key + a sanitized truncated version of the todo_name.

        Raises:
            OSError: if it fails to validate or create the todo folder absolute path.
        """
        if not todo_name or not todo_name.strip():
            raise ValueError("⚠️todo_name cannot be empty or whitespace")

        todo_folder_name: str = self._generate_unique_folder_name(todo_name=todo_name, max_len_code=8,
                                                                  max_len_folder_name=85)

        todo_folder_full_path: Path = self.all_todos_parent_folder_full_path / todo_folder_name

        # Validate target todo folder path or creates it if needed
        try:
            todo_folder_full_path.mkdir(parents=True, exist_ok=True)
            logger.info(f"✅Created folder: {todo_folder_name}")
            # String that will be saved in the SQLite database
            return todo_folder_name

        except OSError as error:
            logger.error(f"🛑Failed to create target directory: {error}")
            raise

    def sanitized_folder_exists(self, todo_folder: str) -> bool:
        """
        Checks and returns boolean value for the existence of a folder related to a todo.

        Args:
            todo_folder : the name that should be linked to a todo, if folder exists

        Returns:
            True or False

        Raises:
            OSError
        """
        # Validation for todo_folder_name
        if not todo_folder or not todo_folder.strip():
            raise ValueError("⚠️todo_folder_name cannot be empty")

        # Security check - prevent directory traversal
        if ".." in todo_folder or "/" in todo_folder or "\\" in todo_folder:
            raise ValueError("⚠️Invalid folder_name: contains path traversal characters")

        folder_path: Path = self.all_todos_parent_folder_full_path / todo_folder

        try:
            if not folder_path.exists():
                logger.info(f"⚠️Folder '{todo_folder}' does not exist.")
                return False

            if not folder_path.is_dir():
                logger.info(f"⚠️Folder '{todo_folder}' exists but is not a directory.")
                return False

            # Returns true if there is a clean safe folder directory existing
            return True

        except OSError as error:
            logger.error(f"🛑Cannot look for '{todo_folder}' folder: {error}.")
            raise

    def temporary_save_uploaded_files(self, e: events.UploadEventArguments) -> None:
        """
        Append ui.upload element's files data to the empty list attached to the FileManager object.

        Args:
            e: events.UploadEventArguments arguments from the 'on_upload' event of the "ui.upload" NiceGUI element.
            It contains, among other things, the name and the content of the uploaded file.

        Returns:
            Nothing.

        Raises:
            AttributeError message, Exception message
        """
        try:
            self.uploaded_files.append({"file_name": e.file.name, "uploaded_file_full_data": e.file})
            logger.info(f"✅Successfully added '{e.file.name}' file to 'uploaded_files' list.")
        except AttributeError as error:
            logger.error(f"🛑Failed to access upload event properties: {error}")
            raise
        except Exception as error:
            logger.error(f"🛑Failed to temporarily save '{e.name}': {error}")
            raise

    async def flush_uploads(self, todo_folder_name: str) -> int | None:
        """
        This method writes/saves locally to a local todo folder the files whose complete data is stored in the
        FileManager object's uploaded_files list.
        Once the files are saved locally in that folder, then the method reset to empty the FileManager object's uploaded_files list.

        Args:
            todo_folder_name (str): will be used to build the files' absolute path that will be saved

        Returns:
            Nothing

        Raises:
            IndexError: not found for the moment a better error exception type.
        """
        # Check if the list attached to the object contains files'data to be saved in the todo folder.
        if not self.uploaded_files:
            logger.warning(f"⚠️No files to save to '{todo_folder_name}' folder.")
            return 0

        # Validation for todo_folder_name
        if not todo_folder_name:
            raise ValueError("todo_folder_name cannot be empty")

        target_folder: Path = self.all_todos_parent_folder_full_path / todo_folder_name
        # Ensure target folder exists
        target_folder.mkdir(parents=True, exist_ok=True)

        files_saved = []

        try:
            for file_data in self.uploaded_files:
                # Build full file path
                file_path: Path = Path(target_folder / file_data["file_name"])

                # Sanitize filename to prevent directory traversal, skips current iteration if risky
                if ".." in file_data["file_name"] or "/" in file_data["file_name"]:
                    logger.warning(f"⚠️Skipping potentially unsafe filename: {file_data['file_name']}")
                    continue

                # Save file locally
                #with open(file_path, "wb") as f:
                    #f.write(file_data["file_content"].read())
                await file_data["uploaded_file_full_data"].save(file_path)
                files_saved.append(file_data["file_name"])  # Add successfully save file to counter

            logger.info(f"✅Successfully saved {len(files_saved)} files to '{todo_folder_name}' folder.")
            return len(files_saved)

        except OSError as error:
            logger.error(f"🛑🛑Failed to save files: {error}")
            raise

        finally:
            # Reset the self.uploaded_files attribute to zero, so it can be used for a new saving process, even if some files failed to save
            self.uploaded_files = []
            logger.info("✅Reset object's uploaded_files list.")

    def delete_folder(self, folder_name: str) -> bool:
        """
        Remove the attachment directory associated with a to-do.
        It first checks if the directory exists before attempting to delete it to prevent errors.

        Args:
            folder_name (str): name of the specific to-do folder to delete.

        Returns:
            bool: True if folder was deleted, False if it didn't exist

        Raises:
            ValueError: If folder_name is empty or invalid
            OSError: If deletion fails due to permissions or other system errors
        """
        # Check if a folder related to the todo exists
        folder_exists: bool = self.sanitized_folder_exists(todo_folder=folder_name)

        # Build the folder path for rmtree
        folder_path: Path = self.all_todos_parent_folder_full_path / folder_name

        try:
            if folder_exists:
                rmtree(folder_path)  # Delete folder and its contents
                logger.info(f"✅Successfully deleted '{folder_name}' folder and all its content.")
                return True
            else:
                logger.info(f"⚠️No '{folder_name}' folder found to be deleted.")
                return False

        except PermissionError as error:
            logger.error(f"🛑 Permission denied deleting folder '{folder_name}': {error}")
            raise OSError(f"Permission denied: {error}") from error

        except OSError as error:
            logger.error(f"🛑 Failed to delete folder '{folder_name}': {error}")
            raise

    def visualize_folder_files_names(self, folder_name: str) -> list:
        """
        Stores inside a list the file names of the files contained in the todo folder.
        If todo folder is empty,

        Args:
            folder_name: to look for the correct folder to  look into

        Returns:
            list: of files names if folder contains files
            str : "Empty" if todo folder is empty

        Raises:
            OSError
        """
        # Validation for todo_folder_name
        if not folder_name or not folder_name.strip():
            raise ValueError("todo_folder_name cannot be empty")

        # Ensure target folder exists
        todo_folder_full_path: Path = self.all_todos_parent_folder_full_path / folder_name
        todo_folder_full_path.mkdir(parents=True, exist_ok=True)

        try:
            # Create a list of all file_names contained in todo_folder and exclude hidden files starting with a "."
            files_in_folder: list = [file_path.name for file_path in todo_folder_full_path.iterdir() if
                                     file_path.is_file() and not file_path.name.startswith(".")]

            if len(files_in_folder) == 0:
                return []
            else:
                return files_in_folder

        except OSError as error:
            logger.error(f"🛑Failed to get what's inside folder '{folder_name}': {error}")
            raise

    def get_folder_files_count(self, folder_name: str) -> int:
        """
        Get the count of files in a todo folder.

        Args:
            folder_name (str): Name of the todo folder to count files in

        Returns:
            int: Number of files in the folder

        Raises:
            ValueError: If folder_name is empty or invalid
            FileNotFoundError: If the folder doesn't exist
            OSError: If there's an error accessing the folder
        """
        folder_exists: bool = self.sanitized_folder_exists(folder_name)

        try:
            if folder_exists:
                files_names: list = self.visualize_folder_files_names(folder_name)
                if len(files_names) == 0:
                    return 0
                else:
                    return len(files_names)

        except (ValueError, FileNotFoundError, OSError):
            # Re-raise the exception from get_folder_files_names
            raise

# if __name__ == "__main__":
#     todo_file_manager = FileManager()
#     a_voir = todo_file_manager.visualize_folder_files_names(folder_name="W5eLSu03_petit_test_des_familles")
#     print(a_voir)
